name: Deploy SIFO DESA to cPanel Hosting

on:
  push:
    branches:
      - utama

jobs:
  deploy:
    name: 🚀 Deploy to Live Server
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📂 FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /public_html/sifo-desa/
          exclude: |
            **/.git*
            **/.git*/**
            **/.vscode/**
            **/node_modules/**
            **/vendor/**
            .env*
            tests/**
            README.md
            ISSUE_TEMPLATE.md
            structura.txt
            asoapsjadkjks
